on:
  pull_request:
    paths:
      - ".github/workflows/go-test.yml"
      - "**.go"
      - "go.mod"
name: Test Go code
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 1.22
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Go fmt
      run: test -z $(gofmt -l .)
    - name: Go test
      run: go test -short -v ./...
